# .github/workflows/daily_prediction.yml
name: Daily KBO Prediction and DB Update

on:
  schedule:
    # UTC 기준 15시 01분에 실행 (서울 시간 00시 01분, 즉 매일 자정 1분)
    - cron: '1 15 * * *'
  workflow_dispatch: # 수동 실행을 허용

jobs:
  run_prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily prediction and DB update
      env:
        DB_URI: ${{ secrets.DB_URI }}
      run: |
        python tasks.py
